# Check the build status of the Bio-Formats test repository job
---
name: Report

on: 
  push:
  schedule:
    - cron: '0 5 * * *'

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check the output of the daily job
        shell: bash
        run: |
          now=$( date '+%F' )
          year=$(date '+%Y')
          wget https://bf-testing-results.s3.amazonaws.com/$year/$now/build-status.log
          output=$(grep "Tests failed in" ./build-status.log)
          if [ -n "$output" ]; then
            exit 1
          fi
        env:
          GH_TOKEN: ${{ github.token }}
